/*
 * windows-tz-map.h
 * This file is part of focal, a calendar application for Linux
 * Copyright 2019 Oliver Giles and focal contributors.
 *
 * Focal is free software: you can redistribute it and/or modify it
 * under the terms of the GNU General Public License version 3 as
 * published by the Free Software Foundation.
 *
 * Focal is distributed without any explicit or implied warranty.
 * You should have received a copy of the GNU General Public License
 * version 3 with focal. If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef WINDOWS_TZ_MAP_H
#define WINDOWS_TZ_MAP_H

#include <string.h>

// We prefer using standard TZIDs such as Europe/Berlin, but when
// interfacing with other systems we might receive timezone names
// like "W. Europe Standard Time". Since we don't know what these mean
// (they don't exist in libical), convert them using a static map.
// The first match from the Unicode CLDR is assumed.

struct windows_tz {
	const char* name; // e.g. "W. Europe Standard Time"
	const char* tzid; // e.g. "Europe/Berlin"
};

// Implementation generated by gperf in windows-tz-map.c
const struct windows_tz* windows_tz_lookup(const char* name, size_t name_len);

#endif //WINDOWS_TZ_MAP_H
